registry:
  url: http://localhost:8081
  addoperationid: add
  searchoperationid: search
  readoperationid: read
keycloak:
  url: https://divoc.xiv.in/keycloak/auth
  authheader: eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJGY2hkNTMyLUZPNXAzaUdOYTZVY01kczFrajRBUzQ1SEQtMUF6OTRZbU5NIn0.eyJleHAiOjE2MDc3NTk1NzIsImlhdCI6MTYwNzU4Njc3MywiYXV0aF90aW1lIjoxNjA3NTg2NzcyLCJqdGkiOiJkZGJiYzBkMy1iMzgwLTQ2MDktYWM3Zi1mMjU5NTVlMDc2OGEiLCJpc3MiOiJodHRwczovL2Rpdm9jLnhpdi5pbi9rZXljbG9hay9hdXRoL3JlYWxtcy9kaXZvYyIsImF1ZCI6ImFjY291bnQiLCJzdWIiOiJjNmM0ZGY4NS02OGUzLTRjN2MtOGM1OS0zNWMwMDM1MzdhYmIiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJmYWNpbGl0eS1hZG1pbi1wb3J0YWwiLCJub25jZSI6IjgwNWNkZTllLWM2ZTgtNDEwNi1hNGU5LWRiODQ1YzA0MzhhNiIsInNlc3Npb25fc3RhdGUiOiI4MWE5ZDM2OC05Y2IyLTQzYWYtYWJjMS0wMTY0MDkyMmQ0YmYiLCJhY3IiOiIxIiwiYWxsb3dlZC1vcmlnaW5zIjpbImh0dHA6Ly9sb2NhbGhvc3Q6ODAwMCIsImh0dHA6Ly9sb2NhbGhvc3Q6MzAwMCIsImh0dHBzOi8vZGl2b2MtcG9ydGFsLnhpdi5pbiJdLCJyZWFsbV9hY2Nlc3MiOnsicm9sZXMiOlsib2ZmbGluZV9hY2Nlc3MiLCJ1bWFfYXV0aG9yaXphdGlvbiJdfSwicmVzb3VyY2VfYWNjZXNzIjp7ImFjY291bnQiOnsicm9sZXMiOlsibWFuYWdlLWFjY291bnQiLCJtYW5hZ2UtYWNjb3VudC1saW5rcyIsInZpZXctcHJvZmlsZSJdfSwiZmFjaWxpdHktYWRtaW4tcG9ydGFsIjp7InJvbGVzIjpbImFkbWluIl19fSwic2NvcGUiOiJvcGVuaWQgcHJvZmlsZSBlbWFpbCIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwicHJlZmVycmVkX3VzZXJuYW1lIjoiMjExMTExMTExMSJ9.ena_S3MaSU6nkARf5Vd3WBpxGgIKd7TRpH5g5w-NJZSunb0QOUg05zCdXH7tUqa7a2t029OVc1rt47KGfAJzWCHRlvV0hkPFcfu6dDgoKCiUhMjdV-2ph250HNGHDw6s_G67ldLOEsHSMEpv_Ep659_l9WiKuYZA32DVVBC7ryuQOq9OlmIlL1HORi8L5r0VZ9oWoRJZSzBI3sGxjofc9KiwZ_SC26729H5DAueIzdOiACHrEE0eefCCSvGLsVR0Mtula8vhd4o-Alne2dScdUB0yjjd5W2nktWymisa6SsD6TZnKD5cgmoiVAyHCA7hF_grLJ9ypH8dxxgNmSHd6w
  recipientgroupid: 7a859744-fae3-4d24-9f1c-4aeed92ba383
kafka:
  bootstrapServers: localhost:9092
  certifyTopic: certify
  eventsTopic: events
  reportedSideEffectsTopic: reported_side_effects
database:
  host: localhost
  port: 5432
  user: postgres
  dbname: postgres
  password: postgres
certificate:
  upload:
     columns: "recipientName,recipientMobileNumber,recipientDOB,recipientGender,recipientNationality,recipientIdentity,vaccinationBatch,vaccinationDate,vaccinationDose,vaccinationTotalDoses,vaccinationEffectiveStart,vaccinationEffectiveEnd,vaccinationManufacturer,vaccinationName,vaccinatorName,facilityName,facilityAddressLine1,facilityAddressLine2,facilityDistrict,facilityState,facilityPincode"
clickhouse:
  dsn: tcp://127.0.0.1:9000?debug=true
