apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: flagr
  name: flagr
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: flagr
  strategy: {}
  template:
    metadata:
      labels:
        k8s-app: flagr
    spec:
      containers:
        - image: checkr/flagr:latest
          imagePullPolicy: Always
          name: flagr
          envFrom:
            - configMapRef:
                name: divoc-config
      restartPolicy: Always
status: {}
