apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: certificate-api
  name: certificate-api
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: certificate-api
  strategy: {}
  template:
    metadata:
      labels:
        k8s-app: certificate-api
    spec:
      containers:
        - image: dockerhub/certificate_api:latest
          imagePullPolicy: Always
          resources:
            requests:
              memory: "64Mi"
              cpu: "400m"
          name: certificate-api
          envFrom:
            - configMapRef:
                name: divoc-config
            - secretRef:
                name: divoc-secrets
      restartPolicy: Always
status: {}
