apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: "2021-01-05T19:47:34Z"
  name: divoc-config
  namespace: divoc
  selfLink: /api/v1/namespaces/divoc/configmaps/divoc-config
  uid: 332a131b-bd4b-4967-8ab8-683da6aa1cec
data:
  DB_HOST: 172.31.25.17
  ENABLE_CERTIFY_ACKNOWLEDGEMENT: ''
  KAFKA_BOOTSTRAP_SERVERS: 172.31.27.143:9092,172.31.26.101:9092,172.31.18.124:9092
  KEYCLOAK_URL: 'http://keycloak-service:8080/auth'
  PUBLIC_KEY: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAhnCjjILI/H3XSG4vlX1UonWWCn1abJKS+yCJHPruJZfTIPC5IF+b6QA2VuOGJhF/+KvPSbSarQ3IuFZA4b/hariahVPfYQJaF9yzVpkVKii67lGq8QpbSs2Y0s9RvNKofhj2GYKT1zSEAA4sWwEC9gMA+B+sJ2pJIc0zFXbcH03aRkeuavxe8dh3QT190SjQioJx4kQyfVtHD5a3ITQIutHOHFLtAXlY9+urvog/0Q5IYf66q2UHxUYisJIyjXYc7yxbYGFnBBRZjm/6R56/MxCnLrhyzQVkFDpRYh8FEJKA3YXYmRKKkFPqpczHNdOsPoqUzoMf+PyIxVr8ihsH4wIDAQAB
  REGISTRY_URL: http://registry:8081
  DISABLE_REGISTRY_CALL: ""
  DIGILOCKER_HMAC_AUTHKEY: "UPDATE_KEY_GIVEN_IN_DIGILOCKER"
  ENABLE_KEYCLOAK: "false"
  CLICK_HOUSE_URL: tcp://172.31.25.17:9000?debug=true
  REDASH_BASE_URL: https://dashboard.divoc.example.com
  REDASH_KEY: ASDFASDF
  CACHE_DURATION_MINUTES: 60
