kafka:
  bootstrapservers: localhost:9092
  notifyTopic: notify
  enrollmenttopic: enrollment
  recipientappointmenttopic: recipientappointment
  certifiedtopic: certified
enrollmentcreation:
  maxretrycount: 10
  lengthofsuffixedenrollmentcode: 3
  maxenrollmentcreationallowed: 4
  maxwalkinenrollmentcreationallowed: 10
auth:
  maxotpverifyattempts: 3
  ttlforotpinminutes: 5
redis:
  redisurl: "redis://0.0.0.0:6379"
  redisPassword: 
registry:
  url: http://localhost:8081
  addoperationid: add
  searchoperationid: search
  readoperationid: read
keycloak:
  url: https://divoc.xiv.in/keycloak/auth
  realm: divoc
log_level: info