galaxy_info:
  role_name: clickhouse
  namespace: alexeysetevoi
  author: Alexey V. Bobrov
  description: Role for installation and managing Yandex.ClickHouse

  license: MIT
  
  min_ansible_version: 2.8

  platforms:
    - name: Ubuntu
      versions:
        - focal
        - bionic
        - xenial
    - name: Debian
      versions:
        - bullseye
        - buster
        - stretch
        - jessie
    - name: EL
      versions:
        - 7
        - 8

  galaxy_tags:
    - clickhouse
    - database
    - sql

dependencies: []
