---

- name: 'Configure Kubectl on kube_control_plane'
  hosts: kube_control_plane
  become: true
  tasks:   
    - name: 'Copy kube config file'
      shell: cp /root/.kube/config /home/ubuntu/kubeadmin.conf

    - name: 'Change permissions for the config file'
      file:
        path: '/home/ubuntu/kubeadmin.conf'
        owner: ubuntu
        mode: 0755

- name: 'Setup docker pull from insecure  registry'
  hosts: kube_control_plane, kube_node, localhost
  become: true
  become_user: root
  tasks:   
    - name: 'create /etc/docker/daemon.json'
      shell: touch /etc/docker/daemon.json
    - name: 'Add insecure access to docker registry'
      shell: |
        echo '{"insecure-registries" : ["{{ registry }}"]}' >> /etc/docker/daemon.json
        service docker restart